SELECT 
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    COALESCE(REVIEW_COMMENT_TITLE , 'no comment title') AS REVIEW_COMMENT_TITLE ,
    COALESCE(REVIEW_COMMENT_MESSAGE , 'no comment message') AS REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE ,
    REVIEW_ANSWER_TIMESTAMP AS REVIEW_ANSWER_DATE,
    CURRENT_TIMESTAMP AS UPDATED_AT

FROM {{source('e_commerece' , 'raw_order_reviews')}}