SELECT 
    PRODUCT_ID,
    INITCAP(PRODUCT_CATEGORY_NAME) AS PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT,
    PRODUCT_DESCRIPTION_LENGHT,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM,
    CURRENT_TIMESTAMP AS UPDATED_AT
FROM {{source('e_commerece' , 'raw_products')}}