WITH GEOLOCATION_INFO AS (
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX,
    GEOLOCATION_LAT,
    GEOLOCATION_LNG,
    GEOLOCATION_CITY,
    GEOLOCATION_STATE,
    AVG(GEOLOCATION_LAT) OVER(PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX ORDER BY GEOLOCATION_ZIP_CODE_PREFIX) AS AVG_GEOLOCATION_LAT,
    AVG(GEOLOCATION_LNG) OVER(PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX ORDER BY GEOLOCATION_ZIP_CODE_PREFIX) AS AVG_GEOLOCATION_LNG,
    ROW_NUMBER() OVER(PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX ORDER BY GEOLOCATION_ZIP_CODE_PREFIX) AS CHOICE,
    UPDATED_AT
FROM {{source('e_commerece' , 'raw_geolocation')}}
ORDER BY GEOLOCATION_ZIP_CODE_PREFIX , CHOICE
) 
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX,
    AVG_GEOLOCATION_LAT AS GEOLOCATION_LAT,
    AVG_GEOLOCATION_LNG AS GEOLOCATION_LNG,
    INITCAP(GEOLOCATION_CITY) AS GEOLOCATION_CITY,
    UPPER(GEOLOCATION_STATE)  AS GEOLOCATION_STATE,
    CURRENT_TIMESTAMP AS UPDATED_AT
FROM GEOLOCATION_INFO
WHERE CHOICE = 1