SELECT 
    INITCAP(REPLACE(PRODUCT_CATEGORY_NAME , '_' , ' ') ) AS PRODUCT_CATEGORY_NAME,
    INITCAP(REPLACE(PRODUCT_CATEGORY_NAME_ENGLISH, '_' , ' ') ) AS PRODUCT_CATEGORY_NAME_ENGLISH,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM {{source('e_commerece' , 'raw_category_name')}}