SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    INITCAP(ORDER_STATUS) AS ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_DATE,
    ORDER_APPROVED_AT AS ORDER_APPROVED_AT_DATE,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE::DATE AS ORDER_ESTIMATED_DELIVERY_DATE,
    CURRENT_TIMESTAMP() AS UPDATED_AT
        

FROM {{source('e_commerece' , 'raw_orders')}}