SELECT
    SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    INITCAP(SELLER_CITY) AS SELLER_CITY,
    UPPER(SELLER_STATE) AS SELLER_STATE,
    CURRENT_TIMESTAMP AS UPDATED_AT
FROM {{source('e_commerece' , 'raw_sellers')}}
