WITH ORDER_DETAILS AS (
SELECT 
    COALESCE(POI.ORDER_ID , PO.ORDER_ID) AS ORDER_ID,
    PO.ORDER_STATUS,
    PO.ORDER_PURCHASE_DATE,
    PO.ORDER_APPROVED_AT_DATE,
    PO.ORDER_DELIVERED_CARRIER_DATE,
    PO.ORDER_DELIVERED_CUSTOMER_DATE,
    PO.ORDER_ESTIMATED_DELIVERY_DATE,
    POI.SHIPPING_LIMIT_DATE,
    MAX(SHIPPING_LIMIT_DATE) OVER(PARTITION BY POI.ORDER_ID ORDER BY POI.ORDER_ID) AS MAX_SHIPPING_LIMIT_DATE,
    COUNT(POI.ORDER_ID) OVER(PARTITION BY POI.ORDER_ID ORDER BY POI.ORDER_ID) AS count_column
FROM {{ref('processed_order_items')}} POI
FULL JOIN {{ref('processed_orders')}} PO 
ON POI.ORDER_ID = PO.ORDER_ID
ORDER BY ORDER_ID
)
SELECT
    DISTINCT 
    ORDER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_DATE,
    ORDER_APPROVED_AT_DATE,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE,
    MAX_SHIPPING_LIMIT_DATE AS SHIPPING_LIMIT_DATE,
    CASE 
        WHEN count_column > 1 THEN 1
        ELSE 0
    END AS is_shipping_limit_delayed
FROM ORDER_DETAILS